In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [53]:
df = pd.read_csv('dataset/data.csv', index_col=0)
df.head()

,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,Club Logo,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,https://cdn.sofifa.org/teams/2/light/241.png,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,https://cdn.sofifa.org/teams/2/light/45.png,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,https://cdn.sofifa.org/teams/2/light/73.png,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,https://cdn.sofifa.org/teams/2/light/11.png,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,https://cdn.sofifa.org/teams/2/light/10.png,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M

In [23]:
df.columns

Index(['ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag', 'Overall',
       'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving', 'GKHandling',
       'GKKicking', 'GKPositioning', 'GKReflexes', 'Release Clause'],
      dtype='object')

In [54]:
df.drop(['ID','Photo','Flag','Club Logo','International Reputation', 'Weak Foot',
        'Work Rate', 'Body Type', 'Real Face','Contract Valid Until'],
       axis=1, inplace=True)

In [55]:
df.drop(['Height', 'Weight'],axis=1, inplace=True)

In [56]:
df.drop(['Preferred Foot'],axis=1, inplace=True)

데이터 없는 행 삭제

In [58]:
nan_data=df.iloc[13236:13284,:]
nan_data.index
df.drop(nan_data.index,inplace = True)

Club 없는 선수들도 삭제

In [60]:
df.Club.isnull().sum()

241

In [61]:
# club nan 행 탐색
df.Club.fillna('non_club', inplace = True)
non_club_s=df[df.Club =='non_club'].index
df.drop(non_club_s,inplace = True)

In [65]:
df.Joined.isnull().sum()

1264

In [76]:
df['Jersey Number'].isnull().sum()

0

value=0인 선수도 삭제(은퇴 직전?)

In [64]:
value_zero=df[df.Value==0].index
df.drop(value_zero, inplace=True)

In [66]:
df.isnull().sum()

Name                 0
Age                  0
Nationality          0
Overall              0
Potential            0
                  ...
GKHandling           0
GKKicking            0
GKPositioning        0
GKReflexes           0
Release Clause    1275
Length: 75, dtype: int64

In [73]:
star=df[df['Position'=='GK'][['Name','Wage','Jersey Number'
                                                       ,'Position','Overall','LS', 'GKDiving']]
star.head(30)

              Name   Wage  Jersey Number Position  Overall    LS  GKDiving
0         L. Messi  €565K           10.0       RF       94  88+2       6.0
2        Neymar Jr  €290K           10.0       LW       92  84+3       9.0
5        E. Hazard  €340K           10.0       LF       91  83+3      11.0
6        L. Modrić  €420K           10.0      RCM       91  77+3      13.0
12        D. Godín  €125K           10.0       CB       90  64+3       6.0
23       S. Agüero  €300K           10.0       ST       89  86+3      13.0
25       K. Mbappé  €100K           10.0       RM       88  85+3      13.0
26        M. Salah  €255K           10.0       RM       88  83+3      14.0
28    J. Rodríguez  €315K           10.0      LAM       88  80+3      15.0
29      L. Insigne  €165K           10.0       LW       88  78+3       8.0
31      C. Eriksen  €205K           10.0      CAM       88  79+3       9.0
58         S. Mané  €195K           10.0       LM       86  81+3      10.0
60     R. Sterling  €195K           10.0       RW       86  76+3      15.0
74         M. Özil  €190K           10.0      CAM       86  75+3       6.0
79   Marco Asensio  €215K           10.0       RW       85  79+3      13.0
90          Parejo   €66K           10.0      RCM       85  74+2       5.0
124       M. Depay   €93K           10.0       ST       84  80+3       8.0
142      E. Banega   €31K           10.0      CDM       84  71+3      13.0
145          Jonas   €25K           10.0       ST       84  82+3      12.0
151       A. Gómez   €53K           10.0       LS       84  75+3       8.0
154      A. Robben  €110K           10.0       RM       84  80+3      10.0
173    Y. Carrasco   €20K           10.0       LM       83  78+3       9.0
244      J. Brandt   €68K           10.0       LM       82  75+2      11.0
253    E. Forsberg   €67K           10.0       LM       82  72+2      13.0
271   Luis Alberto   €67K           10.0       CF       82  77+2       6.0
280       M. Götze   €67K           10.0       CM       82  75+3      14.0
289      A. Ramsey  €130K           10.0      CAM       82  75+3       6.0
292  G. Sigurðsson  €125K           10.0      CAM       82  75+3      13.0
297       M. Kruse   €45K           10.0       ST       82  79+2      12.0
337     João Mário   €71K           10.0      CAM       81  72+3       6.0

In [49]:
Jersey=df[(df['Jersey Number']>11)&(df['Jersey Number']<99)][['Name','Wage','Jersey Number'
                                                       ,'Position','Overall','LS', 'GKDiving']]

In [52]:
Jersey.head(30)

,Name,Wage,Jersey Number,Position,Overall,LS,GKDiving
8,Sergio Ramos,€380K,15.0,RCB,91,73+3,11.0
13,David Silva,€285K,21.0,LCM,90,77+3,6.0
14,N. Kanté,€225K,13.0,LDM,89,72+3,15.0
15,P. Dybala,€205K,21.0,LF,89,83+3,5.0
18,M. ter Stegen,€240K,22.0,GK,89,NaN,87.0
21,E. Cavani,€200K,21.0,LS,89,85+3,12.0
27,Casemiro,€285K,14.0,CDM,88,72+3,13.0
30,Isco,€315K,22.0,LW,88,76+3,10.0
33,P. Aubameyang,€265K,14.0,LM,88,84+3,6.0
35,Marcelo,€285K,12.0,LB,88,80+3,12.0
42,S. Umtiti,€205K,23.0,CB,87,70+3,15.0
44,K. Koulibaly,€115K,26.0,LCB,87,52+3,7.0
48,C. Immobile,€115K,17.0,ST,87,84+3,6.0
49,Jordi Alba,€250K,18.0,LB,87,76+3,13.0
50,D. Mertens,€135K,14.0,RF,87,78+3,7.0
52,M. Hamšík,€125K,17.0,LCM,87,81+3,8.0
55,L. Sané,€195K,19.0,LW,86,82+2,8.0
57,Ederson,€125K,31.0,GK,86,NaN,85.0
64,Alex Sandro,€160K,12.0,LB,86,74+3,7.0
66,T. Müller,€135K,13.0,CAM,86,82+3,6.0
67,Thiago,€130K,19.0,CM,86,75+3,6.0
69,Azpilicueta,€175K,14.0,RB,86,67+3,13.0
70,L. Bonucci,€160K,19.0,RCB,86,65+3,2.0
75,Fernandinho,€185K,25.0,CDM,86,74+3,12.0
77,M. Škriniar,€82K,37.0,LCB,85,57+2,10.0
78,S. Milinković-Savić,€73K,21.0,CM,85,81+2,7.0
80,N. Fekir,€92K,18.0,CAM,85,79+3,15.0
81,Alisson,€115K,13.0,GK,85,NaN,83.0
82,J. Kimmich,€92K,18.0,RCM,85,75+3,8.0
84,R. Mahrez,€205K,26.0,RW,85,77+3,15.0

In [50]:
Jersey['Jersey Number'].describe()

count    11694.000000
mean        26.340944
std         14.363045
min         12.000000
25%         18.000000
50%         23.000000
75%         30.000000
max         98.000000
Name: Jersey Number, dtype: float64

In [51]:
Jersey['Jersey Number'].unique()

array([15., 21., 13., 22., 14., 12., 23., 26., 17., 18., 19., 31., 25.,
       37., 30., 44., 29., 24., 20., 16., 33., 28., 27., 77., 47., 38.,
       40., 92., 36., 87., 34., 32., 83., 70., 35., 89., 56., 57., 91.,
       86., 45., 63., 39., 43., 42., 93., 72., 71., 88., 55., 80., 50.,
       66., 60., 73., 67., 74., 69., 76., 41., 90., 46., 75., 79., 62.,
       81., 61., 49., 95., 53., 96., 97., 68., 98., 94., 58., 78., 48.,
       52., 54., 84., 82., 65., 64., 51., 59., 85.])

In [32]:
df['Jersey Number'].unique()

array([10.,  7.,  1.,  9., 15.,  8., 21., 13., 22.,  5.,  3., 14., 12.,
       11.,  2., 23., 26.,  6., 17., 18.,  4., 19., 31., 25., 37., 30.,
       44., 29., 24., 20., 16., 33., 28., 27., 77., 47., 38., 40., 92.,
       36., 87., 34., 32., 83., 70., 35., 89., 56., 99., 57., 91., 86.,
       45., 63., 39., 43., 42., 93., 72., 71., 88., 55., 80., 50., 66.,
       60., 73., 67., 74., 69., 76., 41., 90., 46., 75., 79., 62., 81.,
       61., 49., 95., 53., 96., 97., 68., 98., 94., 58., 78., nan, 48.,
       52., 54., 84., 82., 65., 64., 51., 59., 85.])

In [ ]:
df1=df[['LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB']]